server:
  port: 8080
  servlet:
    context-path: /api # 添加全局接口前缀
    session:
      cookie:
        domain:
          - localhost
          - 127.0.0.1

spring:
  profiles:
    active: dev
  application:
    name: companion-backend
  # Mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/companion?serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
    username: root
    password: 123456
    #    url: jdbc:mysql://47.121.29.243:3306/companion?serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
    #    username: companion
    #    password: 123456
    # 连接池
    hikari:
      minimum-idle: 5 # 最小空闲连接数
      maximum-pool-size: 10 # 最大活跃连接数
      connection-timeout: 30000 # 连接超时时间（毫秒）
      idle-timeout: 600000 # 空闲连接最大存活时间
      auto-commit: true # 此属性控制从池返回的连接的默认自动提交行为
  # redis
  redis:
    port: 6379
    host: 127.0.0.1
    database: 0
  # session 配置
  session:
    timeout: 86400 # 过期时间：2天
    store-type: redis
  mvc:
    path match:
      matching-strategy: ant_path_matcher

# mybatis-plus配置
mybatis-plus:
  configuration:
    mapUnderscoreToCamelCase: false # 是否开启自动驼峰命名规则，默认为true
  #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 打印sql日志
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

# 七牛云配置
oss:
  qiniu:
    accessKey: Fkp7JqTAEfWPn2hmQ0JtfkbBfzcMWgG6fPBqph2k # 公钥
    secretKey: jyXRFDEpdHiOYY-HxKxlr9bgw6Hak1_mnmJRfXld # 私钥
    bucketName: companion-storage # 创建的对象存储的空间名称
    path: shq2sf8gm.hn-bkt.clouddn.com #